inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.3
  NewCops: enable

  Exclude:
    - "bin/*"
    - "README.md"
    - "spec/**/*"
    - "vendor/**/*"

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
